### ISSUE TITLE
Deprecations with Blacklight 7.9

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/blacklight-hierarchy#27]
```
DEPRECATION WARNING: facet_in_params? is deprecated and will be removed from blacklight 8.0. (called from render_facet_hierarchy_item at /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:16) (8 times); e.g.:
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:16:in `render_facet_hierarchy_item'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:24:in `block in render_facet_hierarchy_item'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:23:in `collect'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:23:in `render_facet_hierarchy_item'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:42:in `block in render_hierarchy'

DEPRECATION WARNING: path_for_facet is deprecated and will be removed from blacklight 8.0. (called from render_qfacet_value at /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:48) (8 times); e.g.:
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:48:in `render_qfacet_value'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:19:in `render_facet_hierarchy_item'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:24:in `block in render_facet_hierarchy_item'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:23:in `collect'
    /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/blacklight-hierarchy-4.1.0/app/helpers/blacklight/hierarchy_helper.rb:23:in `render_facet_hierarchy_item'
```

**Comment by cbeer** [comment]
We might also decide to deprecate the whole gem. The new pivot facet component has the UI elements from this and just needs something to build up a facet item hierarchy

**Comment by jcoyne** [comment]
@cbeer until that happens, it would still be nice to avoid the deprecation warnings.
